### PR TITLE
Uncomment MessageCredentialType.IssuedToken for WSHttpBinding

### PR DESCRIPTION
**Pull request by emre-toraman**
Fixes https://github.com/CoreWCF/CoreWCF/issues/1317

### CODE REVIEW

**Comment by emre-toraman** [comment]
@dotnet-policy-service agree company="SOTI"

**Comment by emre-toraman** [comment]
@birojnayak Thank you for your comment in https://github.com/CoreWCF/CoreWCF/issues/1317#issuecomment-1900603033, I created the PR as you suggested. Can you please review and advise?

**Comment by birojnayak** [comment]
@emre-toraman have you tested internally ? Is there a possibility to add test ?

**Comment by emre-toraman** [comment]
@birojnayak I have tested two things internally:

- I was able to start WebApplication with a service that uses
```
var httpBinding = new WSHttpBinding(SecurityMode.TransportWithMessageCredential);
httpBinding.Security.Message.ClientCredentialType = MessageCredentialType.IssuedToken;
```

- I was able to create binding elements from above binding:
```
var bindingElementCollection = httpBinding.CreateBindingElements()
```

I'm not sure how to create a client for this service though. Do you have any client sample for this configuration?

**Comment by birojnayak** [comment]
@emre-toraman I assume you have a client which is connecting to your existing WCF service, you can run the same client pointing to CoreWCF service. If that works let me know, happy to approve the PR. 

I understand testing token is bit tricky and needs set up. While porting WS-Fed binding, I had written some test [here](https://github.com/CoreWCF/CoreWCF/blob/main/src/CoreWCF.Http/tests/SimpleWSFedBinding.cs#L38). See if this could be useful.

**Pull request merged**
