### PR TITLE
Ensure net60 support & drop netcoreapp2.1 from unit tests

### PR DESCRIPTION
**Pull request by g7ed6e**

### CODE REVIEW

**Comment by g7ed6e** [comment]
@mconnew As discussed i dropped netcoreapp2.1 target from unit tests.

**Comment by g7ed6e** [comment]
I just noticed the `Coverage` stage was broken. It is fixed now.

**Comment by mconnew** [comment]
Thank you for fixing the coverage stage. It will be great to see how our code coverage is again.

**Comment by g7ed6e** [comment]
I was referring to the `Coverage` stage that was ran with this branch PR build pipeline (.net 6 sdk was missing in that stage and PR build was broken). 
I'm sorry for confusion. 
I will have a look to fix the coverage stage.

**Pull request merged**
