### PR TITLE
pass through quotas for the NetHttpBinding

### PR DESCRIPTION
**Pull request by 0x53A**
ref https://github.com/CoreWCF/CoreWCF/issues/113

This is what I changed locally to get it to work. Not quite sure what to do about the BasicHttpBinding.

### CODE REVIEW

**Comment by mconnew** [comment]
This isn't quite the correct solution. The full implementation should live on HttpBindingBase. You can find the original code [here](https://referencesource.microsoft.com/#System.ServiceModel/System/ServiceModel/HttpBindingBase.cs,52817be0254871f7). That way you don't need to override it. That code sets it on the text message encoder too so it will apply for BasicHttpBinding too.

**Comment by 0x53A** [comment]
Okay I tried to adapt it to be similar to the reference source.

mtom doesn't (yet) seem to be implemented in CoreWCF, whatever it is, and HttpBindingBase._httpsTransport is null, so I just commented that code also out.

**Comment by mconnew** [comment]
I realized this still isn't going to get the job done for you. The SetReaderQuotas method isn't currently being called. I'm working on a set of changes to fix that. The reader quota's are just set on the binary message encoder so today you could just do this:
```c#
var netHttpBinding = new NetHttpBinding();
var customBinding = new CustomBinding(netHttpBinding);
var bmebe = customBinding.Elements.Find<BinaryMessageEncodingBindingElement>();
bmebe.ReaderQuotas = myReaderQuotas;
```
Then use customBinding for your endpoint. 
There's an unrelated failing test (InstanceProviderReleaseCalledWithCorrectObjectTest) which is a race condition in the test showing up because of some recent performance improvements so I'm going to merge this as it takes us a step closer even though it doesn't solve your problem fully.

**Comment by 0x53A** [comment]
> [...] The SetReaderQuotas method isn't currently being called. [...]

It is called in the setter of HttpBindingBase.ReaderQuotas, so I think it should actually work right now as is, but I didn't test it tbh.

My service seems to work for now, thank you for this project!

**Comment by absinghal** [comment]
There seems to be another issue in NetHttpBinding with BinaryEncoding

The following code runs before _maxReceivedMessageSize is set by SetMaxReceivedMessageSizeFromTransport

``` var httpSettings = new HttpTransportSettings
            {
                BufferManager = BufferManager.CreateBufferManager(DefaultMaxBufferPoolSize, tbe.MaxBufferSize),
                OpenTimeout = _serviceDispatcher.Binding.OpenTimeout,
                ReceiveTimeout = _serviceDispatcher.Binding.ReceiveTimeout,
                SendTimeout = _serviceDispatcher.Binding.SendTimeout,
                CloseTimeout = _serviceDispatcher.Binding.CloseTimeout,
                MaxBufferSize = tbe.MaxBufferSize,
                MaxReceivedMessageSize = tbe.MaxReceivedMessageSize,
                MessageEncoderFactory = mebe.CreateMessageEncoderFactory(),
                ManualAddressing = tbe.ManualAddressing,
                TransferMode = tbe.TransferMode,
                KeepAliveEnabled = tbe.KeepAliveEnabled,
                AnonymousUriPrefixMatcher = new HttpAnonymousUriPrefixMatcher(),
                AuthenticationScheme = tbe.AuthenticationScheme,
                WebSocketSettings = tbe.WebSocketSettings.Clone()
            };
```

So the factory is initialized with MaxReceivedMessageSize =0
and so BinaryMessageEncoder also has  _maxReceivedMessageSize =0 
So this combination does not work

As a workaround for now, have set _maxReceivedMessageSize using reflection in my application

**Pull request merged**
