### PR TITLE
Create stale.yml

### PR DESCRIPTION
**Pull request by g7ed6e**

### CODE REVIEW

**Comment by mconnew** [comment]
Will this mark an issue as stale if the original author has posted a reply and I don't get to quickly?

**Comment by mconnew** [comment]
Btw, as long as debug-only is set to true, don't wait for me to approve any changes to stale.yml to merge it. There will be some experimenting and you shouldn't be blocked on me to try things.

**Review by mconnew — APPROVED** [review]
Approving as this is debug-only so won't break anything.

**Comment by g7ed6e** [comment]
> Will this mark an issue as stale if the original author has posted a reply and I don't get to quickly?

@mconnew The counter starts (or is reset) according to the updated_at value of an issue. I'm understanding that any activity on the issue will reset the counter.

**Pull request merged**
