### PR TITLE
Add NuGet package status

### PR DESCRIPTION
**Pull request by paulomorgado**

### CODE REVIEW

**Comment by mconnew** [comment]
I think this should be a bit more prominent. I don't think you should have to scroll to get to this info. Can you place it just before the announcements section?

**Comment by paulomorgado** [comment]
> I think this should be a bit more prominent. I don't think you should have to scroll to get to this info. Can you place it just before the announcements section?

Done!

**Comment by mconnew** [comment]
Thank you for this. Sometimes I get too focused on the code implementation and don't take a step back to look at other areas to improve.

**Comment by paulomorgado** [comment]
That's the value of open-source and community.

**Pull request merged**
