### PR TITLE
Adding support ConfigurationManager based config

### PR DESCRIPTION
**Pull request by Ximik87**
This feature adding support ConfigurationManager config files from .Net Framework. (Issues #129 )
Now is supported (basic scenario):
BindingsSection - BasicHttpBinding, NetHttpBinding, NetTcpBinding, WSHttpBinding
ServicesSection - Service and endpoint

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/CoreWCF/CoreWCF?pullRequest=364) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/CoreWCF/CoreWCF?pullRequest=364) before we can accept your contribution.<br/><br/>:x: Ximik87 [sign now](https://cla.dotnetfoundation.org/CoreWCF/CoreWCF?pullRequest=364)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/CoreWCF/CoreWCF?pullRequest=364) it.</sub>

**Comment by birojnayak** [comment]
> This feature adding support ConfigurationManager config files from .Net Framework. (Issues #129 )
> Now is supported (basic scenario):
> BindingsSection - BasicHttpBinding, NetHttpBinding, NetTcpBinding, WSHttpBinding
> ServicesSection - Service and endpoint



> This feature adding support ConfigurationManager config files from .Net Framework. (Issues #129 )
> Now is supported (basic scenario):
> BindingsSection - BasicHttpBinding, NetHttpBinding, NetTcpBinding, WSHttpBinding
> ServicesSection - Service and endpoint

will start reviewing... thanks !

**Comment by mconnew** [comment]
@Ximik87, this is fantastic. It's going to take a little time to review as I want to understand how it all fits together. There's some conflicts with the head of main so the tests can't run. You also have a large number of commits. Would you be able to squash your commits and rebase on to master as it will make reviewing a little easier?

**Comment by Ximik87** [comment]
Sorry, I tried to squash commits. In result history git on fail. I'm creating new pull request for clean history.

**Pull request closed without merging**
