### PR TITLE
Send and receieve zero and non-zero streams over a request/reply cont…

### PR DESCRIPTION
**Pull request by v-fangfc**
@mconnew @HongGit

### CODE REVIEW

**Comment by v-fangfc** [comment]
@mconnew , with config "MessageEncodingBindingElement encodingBindingElement = new TextMessageEncodingBindingElement(messageVersion, Encoding.Unicode); httpTransportBindingElement.TransferMode = TransferMode.Streamed;" applied in service, I get the following exception in netcoreapp3.0, is it a bug?
 Message: 
    System.ServiceModel.CommunicationException : Unrecognized message version.
  Stack Trace: 
    ReceivedMessage.ReadStartEnvelope(XmlDictionaryReader reader)
    StreamedMessage.ctor(XmlDictionaryReader reader, Int32 maxSizeOfHeaders, MessageVersion desiredVersion)
    Message.CreateMessage(XmlDictionaryReader envelopeReader, Int32 maxSizeOfHeaders, MessageVersion version)
    Message.CreateMessage(XmlReader envelopeReader, Int32 maxSizeOfHeaders, MessageVersion version)
    TextMessageEncoder.ReadMessage(Stream stream, Int32 maxSizeOfHeaders, String contentType)
    MessageEncoder.ReadMessageAsync(Stream stream, Int32 maxSizeOfHeaders, String contentType)
    HttpResponseMessageHelper.ReadStreamedMessageAsync(Task`1 inputStreamTask)
    HttpResponseMessageHelper.ParseIncomingResponse(TimeoutHelper timeoutHelper)
    HttpClientChannelAsyncRequest.ReceiveReplyAsync(TimeoutHelper timeoutHelper)
    RequestChannel.RequestAsync(Message message, TimeSpan timeout)
    RequestChannel.RequestAsyncInternal(Message message, TimeSpan timeout)
    TaskHelpers.WaitForCompletionNoSpin[TResult](Task`1 task)
    RequestChannel.Request(Message message, TimeSpan timeout)
    RequestChannelBinder.Request(Message message, TimeSpan timeout)
    ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
    ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs)
    ServiceChannelProxy.InvokeService(MethodCall methodCall, ProxyOperationRuntime operation)
    ServiceChannelProxy.Invoke(MethodInfo targetMethod, Object[] args)
    --- End of stack trace from previous location where exception was thrown ---
    DispatchProxyGenerator.Invoke(Object[] args)
    generatedProxy_1.Echo(Stream )

**Comment by mconnew** [comment]
/azp run
This should pass now I've (hopefully) fixed the flakey test.

**Pull request merged**
