### PR TITLE
Set up CI with Azure Pipelines

### PR DESCRIPTION
**Pull request by mconnew**

### CODE REVIEW

**Comment by Daniel-Svensson** [comment]
Good to see everything is up and running 👍 
@mconnew will you make the devops project (pipeline) public so everyone can look at the build results and test outcomes.

**Comment by mconnew** [comment]
I'm not the sole owner of this project so I can't name the decision in isolation but that would be my preference.

**Comment by tibor19** [comment]
> I'm not the sole owner of this project so I can't make the decision in isolation but that would be my preference.

I am OK with that as well!

**Comment by mconnew** [comment]
Closing as pipelines have been enabled in the master branch now.

**Pull request closed without merging**
