### PR TITLE
Fix Templates pipeline

### PR DESCRIPTION
**Pull request by g7ed6e**

### CODE REVIEW

**Review by mconnew — APPROVED** [review]

**Comment by g7ed6e** [comment]
@mconnew this PR removes the azdo pipeline dedicated to templates too. The stage that run templates tests is ran conncurrently to the product unit tests.

**Comment by mconnew** [comment]
The test that failed was due to #1376. I suspect we're going to see more of this in future.

**Review by mconnew — APPROVED** [review]

**Pull request merged**
