### PR TITLE
typo: Addresss -> Address

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by mconnew** [comment]
Some of these files are disappearing with PR #13. This is the same with some of your other PR's. Can you hold off until that PR is merged. Also in future can you combine multiple minor changes of the same class (eg typo fixes) into a single PR. It makes reviewing take less time. Especially on mobile.

**Comment by mconnew** [comment]
Btw, thank you for this. Things like typos often get ignored as unimportant.

**Comment by mconnew** [comment]
I've just merged an earlier PR which conflicts. Please rebase.

**Comment by nschonni** [comment]
@mconnew rebased. I'll try and lump them together going forward

**Pull request merged**
