### PR TITLE
Make public CustomUserNameSecurityTokenAuthenticator

### LINKED ISSUE #571: CustomUserNameSecurityTokenAuthenticator is internal
I'm in the process of converting our WCF security model over to CoreWCF and have hit a wall because `CustomUserNameSecurityTokenAuthenticator` has been marked as internal.

I'm unable to work around it by inheriting from a class further up the chain because the `UserNameSecurityToken` is also marked as internal, and that is the token type which will get created.

Is there a reason why these are marked as internal?

### PR DESCRIPTION
**Pull request by lucashigor**
Make public CustomUserNameSecurityTokenAuthenticator 

Is related to issue: 

~https://github.com/CoreWCF/CoreWCF/pull/1419~
resolves #571

### CODE REVIEW

**Comment by lucashigor** [comment]
> @lucashigor please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @dotnet-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @dotnet-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @dotnet-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement
@dotnet-policy-service agree

**Comment by g7ed6e** [comment]
Hi @lucashigor . Thanks you for submitting that PR.
Do you think you can add a unit test that uses the public API ?

**Review by birojnayak — APPROVED** [review]
looks ok to me

**Comment by birojnayak** [comment]
> Hi @lucashigor . Thanks you for submitting that PR. Do you think you can add a unit test that uses the public API ?

(https://github.com/CoreWCF/CoreWCF/blob/2d68db4fe2018fa9f7a70d83af652ce7d9c294ff/src/CoreWCF.Http/tests/SimpleWSHTTPTest.cs#L145) this covers the internal functionalities of the Authenticator.

**Comment by mconnew** [comment]
Would you also want to make UserNameSecurityToken public as part of this PR too?

**Pull request merged**
