### PR TITLE
Challenge unauthenticated requests when using InheritedFromHost

### PR DESCRIPTION
**Pull request by g7ed6e**

### CODE REVIEW

**Review by mconnew — APPROVED** [review]

**Comment by mconnew** [comment]
Did you mean for this to still be a draft PR?

**Comment by g7ed6e** [comment]
> Did you mean for this to still be a draft PR?

No, I forgot to publish.

**Comment by g7ed6e** [comment]
> Did you mean for this to still be a draft PR?

Yes i want to add defensive tests with interceptors introduced in #948

**Comment by g7ed6e** [comment]
> Did you mean for this to still be a draft PR?

@mconnew i added the defensive tests

**Review by mconnew — APPROVED** [review]

**Comment by mconnew** [comment]
Please squash and merge

**Pull request merged**
